// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOi7KRQDHDHCnvXH0OT-z9uG9JbZd3SGU',
    appId: '1:764062822397:web:6585470dcc90c0c9d43394',
    messagingSenderId: '764062822397',
    projectId: 'sunnah-diet',
    authDomain: 'sunnah-diet.firebaseapp.com',
    storageBucket: 'sunnah-diet.appspot.com',
    measurementId: 'G-TQ8QHF3SD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDMpT2KYz4uzszVo8Zd6wdzWoHJygriSU',
    appId: '1:764062822397:android:2ce3ce709b9b8479d43394',
    messagingSenderId: '764062822397',
    projectId: 'sunnah-diet',
    storageBucket: 'sunnah-diet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJvg0W8n2RfrbSBBzWE9J1atcGHpsY4Go',
    appId: '1:764062822397:ios:d0e3356330c45d3fd43394',
    messagingSenderId: '764062822397',
    projectId: 'sunnah-diet',
    storageBucket: 'sunnah-diet.appspot.com',
    iosBundleId: 'com.example.sunnahDiet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJvg0W8n2RfrbSBBzWE9J1atcGHpsY4Go',
    appId: '1:764062822397:ios:1bd1642ec271d302d43394',
    messagingSenderId: '764062822397',
    projectId: 'sunnah-diet',
    storageBucket: 'sunnah-diet.appspot.com',
    iosBundleId: 'com.example.sunnahDiet.RunnerTests',
  );
}
